# Generated by Django 3.2 on 2022-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_email', models.EmailField(default='webbogdan11@gmail.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
